//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _2024_08_20Final1
{
    public partial class About
    {
    }
}
